//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxiteHR.GlobalizationResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxiteHR.GlobalizationResources.Resources.AuthResources", typeof(AuthResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail address or password..
        /// </summary>
        public static string InvalidMailOrPassword {
            get {
                return ResourceManager.GetString("InvalidMailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid E-Mail address or Password.
        /// </summary>
        public static string LoginInvalidData {
            get {
                return ResourceManager.GetString("LoginInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Firmy.
        /// </summary>
        public static string Model_CompanyId {
            get {
                return ResourceManager.GetString("Model_CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Model_Email {
            get {
                return ResourceManager.GetString("Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Model_FirstName {
            get {
                return ResourceManager.GetString("Model_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Model_LastName {
            get {
                return ResourceManager.GetString("Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Model_Password {
            get {
                return ResourceManager.GetString("Model_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Model_PhoneNumber {
            get {
                return ResourceManager.GetString("Model_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Model_UserName {
            get {
                return ResourceManager.GetString("Model_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Model_UserPasswordRepeated {
            get {
                return ResourceManager.GetString("Model_UserPasswordRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during password change. Please try again later..
        /// </summary>
        public static string PasswordChangeGlobalError {
            get {
                return ResourceManager.GetString("PasswordChangeGlobalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with passed E-Mail address exists in the application.
        /// </summary>
        public static string RegisterEmailExistsInDb {
            get {
                return ResourceManager.GetString("RegisterEmailExistsInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during user registration. Please try again later..
        /// </summary>
        public static string RegisterGlobalError {
            get {
                return ResourceManager.GetString("RegisterGlobalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with the specified username already exists in the application..
        /// </summary>
        public static string RegisterUserNameExistsInDb {
            get {
                return ResourceManager.GetString("RegisterUserNameExistsInDb", resourceCulture);
            }
        }
    }
}
