//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxiteHR.GlobalizationResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompanyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxiteHR.GlobalizationResources.Resources.CompanyResources", typeof(CompanyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanowisko pracy już istnieje dla firmy.
        /// </summary>
        public static string CompanyRoleCreate_CompanyRoleCompanyExists {
            get {
                return ResourceManager.GetString("CompanyRoleCreate_CompanyRoleCompanyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have permission to create a new role..
        /// </summary>
        public static string CompanyRoleCreate_UserDoesntHavePermissions {
            get {
                return ResourceManager.GetString("CompanyRoleCreate_UserDoesntHavePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating a new company. Please try again later..
        /// </summary>
        public static string NewCompanyCreate_InternalError {
            get {
                return ResourceManager.GetString("NewCompanyCreate_InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID.
        /// </summary>
        public static string NewEmployeeRequestDto_CompanyId {
            get {
                return ResourceManager.GetString("NewEmployeeRequestDto_CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string NewEmployeeRequestDto_Email {
            get {
                return ResourceManager.GetString("NewEmployeeRequestDto_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string NewEmployeeRequestDto_FirstName {
            get {
                return ResourceManager.GetString("NewEmployeeRequestDto_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string NewEmployeeRequestDto_LastName {
            get {
                return ResourceManager.GetString("NewEmployeeRequestDto_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string NewEmployeeRequestDto_PhoneNumber {
            get {
                return ResourceManager.GetString("NewEmployeeRequestDto_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to register the user. Please try again later..
        /// </summary>
        public static string NewEmployeeRequestDto_RegisterError {
            get {
                return ResourceManager.GetString("NewEmployeeRequestDto_RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string NewEmployeeRequestDto_UserName {
            get {
                return ResourceManager.GetString("NewEmployeeRequestDto_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with passed E-Mail address exists in the application.
        /// </summary>
        public static string RegisterEmailExistsInDb {
            get {
                return ResourceManager.GetString("RegisterEmailExistsInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during user registration. Please try again later..
        /// </summary>
        public static string RegisterGlobalError {
            get {
                return ResourceManager.GetString("RegisterGlobalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with the specified username already exists in the application..
        /// </summary>
        public static string RegisterUserNameExistsInDb {
            get {
                return ResourceManager.GetString("RegisterUserNameExistsInDb", resourceCulture);
            }
        }
    }
}
