//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxiteHR.GlobalizationResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxiteHR.GlobalizationResources.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must match the {1} field..
        /// </summary>
        public static string Global_CompareField {
            get {
                return ResourceManager.GetString("Global_CompareField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting user ID.
        /// </summary>
        public static string Global_InsUserId {
            get {
                return ResourceManager.GetString("Global_InsUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string Global_InvalidEmailAddress {
            get {
                return ResourceManager.GetString("Global_InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be at most {1} characters long..
        /// </summary>
        public static string Global_MaxLengthField {
            get {
                return ResourceManager.GetString("Global_MaxLengthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be at least {1} characters long..
        /// </summary>
        public static string Global_MinLengthField {
            get {
                return ResourceManager.GetString("Global_MinLengthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is missing..
        /// </summary>
        public static string Global_MissingToken {
            get {
                return ResourceManager.GetString("Global_MissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authenticated..
        /// </summary>
        public static string Global_NotAuthorizedError {
            get {
                return ResourceManager.GetString("Global_NotAuthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period from.
        /// </summary>
        public static string Global_PeriodFrom {
            get {
                return ResourceManager.GetString("Global_PeriodFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period to.
        /// </summary>
        public static string Global_PeriodTo {
            get {
                return ResourceManager.GetString("Global_PeriodTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested user does not exist in application.
        /// </summary>
        public static string Global_RequestedUserDoesNotExistsInDb {
            get {
                return ResourceManager.GetString("Global_RequestedUserDoesNotExistsInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string Global_RequiredField {
            get {
                return ResourceManager.GetString("Global_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged user don&apos;t have permission to do this operation..
        /// </summary>
        public static string Global_UserWithoutPermission {
            get {
                return ResourceManager.GetString("Global_UserWithoutPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world!.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
    }
}
