// <auto-generated />
using System;
using AxiteHR.Services.CompanyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AxiteHR.Services.CompanyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240901121217_IsSupervisorColumnForCompanyUserRole")]
    partial class IsSupervisorColumnForCompanyUserRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyLevelId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyLevelId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxNumberOfWorkers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxNumberOfWorkers = 10
                        },
                        new
                        {
                            Id = 2,
                            MaxNumberOfWorkers = 25
                        },
                        new
                        {
                            Id = 3,
                            MaxNumberOfWorkers = 50
                        },
                        new
                        {
                            Id = 4,
                            MaxNumberOfWorkers = 100
                        },
                        new
                        {
                            Id = 5,
                            MaxNumberOfWorkers = 2147483647
                        });
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyPermission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionName = "CompanyManager"
                        },
                        new
                        {
                            Id = 2,
                            PermissionName = "Employee"
                        });
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMain = false,
                            IsVisible = false,
                            RoleName = "Company creator"
                        },
                        new
                        {
                            Id = 2,
                            IsMain = true,
                            IsVisible = true,
                            RoleName = "Software department"
                        });
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyUserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyPermissionId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPermissionId");

                    b.HasIndex("CompanyUserId");

                    b.ToTable("CompanyUserPermissions");
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyRoleId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyRoleId");

                    b.HasIndex("CompanyUserId");

                    b.ToTable("CompanyUserRoles");
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.Company", b =>
                {
                    b.HasOne("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyLevel", "CompanyLevel")
                        .WithMany()
                        .HasForeignKey("CompanyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyLevel");
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyUser", b =>
                {
                    b.HasOne("AxiteHr.Services.CompanyAPI.Models.CompanyModels.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyUserPermission", b =>
                {
                    b.HasOne("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyPermission", "CompanyPermission")
                        .WithMany()
                        .HasForeignKey("CompanyPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyUser", "CompanyUser")
                        .WithMany()
                        .HasForeignKey("CompanyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyPermission");

                    b.Navigation("CompanyUser");
                });

            modelBuilder.Entity("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyUserRole", b =>
                {
                    b.HasOne("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyRole", "CompanyRole")
                        .WithMany()
                        .HasForeignKey("CompanyRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AxiteHr.Services.CompanyAPI.Models.CompanyModels.CompanyUser", "CompanyUser")
                        .WithMany()
                        .HasForeignKey("CompanyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyRole");

                    b.Navigation("CompanyUser");
                });
#pragma warning restore 612, 618
        }
    }
}
