// <auto-generated />
using System;
using AxiteHR.Services.CompanyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AxiteHR.Services.CompanyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241124155700_CompanyRoleAddColumnRoleNameEng")]
    partial class CompanyRoleAddColumnRoleNameEng
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyLevelId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyLevelId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxNumberOfWorkers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxNumberOfWorkers = 10
                        },
                        new
                        {
                            Id = 2,
                            MaxNumberOfWorkers = 25
                        },
                        new
                        {
                            Id = 3,
                            MaxNumberOfWorkers = 50
                        },
                        new
                        {
                            Id = 4,
                            MaxNumberOfWorkers = 100
                        },
                        new
                        {
                            Id = 5,
                            MaxNumberOfWorkers = 2147483647
                        });
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyPermission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CompanyPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionName = "CompanyManager"
                        },
                        new
                        {
                            Id = 2,
                            PermissionName = "Employee"
                        });
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoleNameEng")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CompanyRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Company creator",
                            RoleNameEng = ""
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Software department",
                            RoleNameEng = ""
                        });
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyRoleCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyRoleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyRoleId", "CompanyId")
                        .IsUnique();

                    b.ToTable("CompanyRoleCompanies");
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyUserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyPermissionId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPermissionId");

                    b.HasIndex("CompanyUserId");

                    b.ToTable("CompanyUserPermissions");
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyRoleCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyRoleCompanyId");

                    b.HasIndex("CompanyUserId");

                    b.ToTable("CompanyUserRoles");
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.Company", b =>
                {
                    b.HasOne("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyLevel", "CompanyLevel")
                        .WithMany()
                        .HasForeignKey("CompanyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyLevel");
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyRoleCompany", b =>
                {
                    b.HasOne("AxiteHR.Services.CompanyAPI.Models.CompanyModels.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyRole", "CompanyRole")
                        .WithMany()
                        .HasForeignKey("CompanyRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CompanyRole");
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyUser", b =>
                {
                    b.HasOne("AxiteHR.Services.CompanyAPI.Models.CompanyModels.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyUserPermission", b =>
                {
                    b.HasOne("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyPermission", "CompanyPermission")
                        .WithMany()
                        .HasForeignKey("CompanyPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyUser", "CompanyUser")
                        .WithMany()
                        .HasForeignKey("CompanyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyPermission");

                    b.Navigation("CompanyUser");
                });

            modelBuilder.Entity("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyUserRole", b =>
                {
                    b.HasOne("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyRoleCompany", "CompanyRoleCompany")
                        .WithMany()
                        .HasForeignKey("CompanyRoleCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AxiteHR.Services.CompanyAPI.Models.CompanyModels.CompanyUser", "CompanyUser")
                        .WithMany()
                        .HasForeignKey("CompanyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyRoleCompany");

                    b.Navigation("CompanyUser");
                });
#pragma warning restore 612, 618
        }
    }
}
